openapi: 3.0.3
info:
  title: Swagger Fake SalesForce - OpenAPI 3.0
  description: |-
    Swagger Fake SalesForce - OpenAPI 3.0.
  version: 1.0.0
servers:
  - url: https://api-test-salesforce.vercel.app
  - url: http://localhost:3000
paths:
  /services/oauth2/token:
    post:
      summary: Lấy JWT access_token và instance_url test.salesforce.com
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  description: Kiểu grant OAuth2
                assertion:
                  type: string
                  description: JWT hoặc chứng thực để lấy token
              required:
                - grant_type
                - assertion
      responses:
        200:
          description: Trả về JWT access_token và instance_url
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT được tạo để truy cập
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  instance_url:
                    type: string
                    description: URL của instance Salesforce
                    example: https://test.salesforce.com
        400:
          description: Thiếu tham số hoặc tham số không hợp lệ
